name: GitHubActions_Test1
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deplay_ver_${{ github.sha }}" 

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my reppo
        uses: actions/checkout@v1
        
      - name: Print Hello Messege in my_testing
        run: echo "Hello World! from testing"
        
      - name: Execute few commands
        run: |
          echo "Hello Messege1"
          echo "Hello Messege2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
        
      - name: List current folder
        run: ls -la
        
        
  my_testint2:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job Level Variable1"
      VAR2: "This is Job Level Variable2"
    
    steps:
      - name: Print Hello Messege in my_testing2
        run: echo "Hello World! from testing2"
    
      - name: Prirnt env VARs
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is super-local env"
          
          
        
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
      
      - name: Lets test some packages if they are here 1
        run: aws --version
        
      - name: Lets test some packages if there are here 2
        run: zip --version
        
        
