name: GitHubActions_Test1

on:
  push:
    branches: 
      - master

jobs:
  code_check:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      
      - name: Install Frameworks
        run: |
          pip install mypy
          pip install flake8
          pip install isort
          pip install pytest
      
      - name: Mypy check
        run: mypy .
        
      - name: Flake8 check
        run: flake8 .
      
      - name: ISort check
        run: isort .
      
      - name: Testing the code
        run: pytest .
        
