name: GitHubActions_Test1
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deplay_ver_${{ github.sha }}" 

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Messege in my_testing
        run: echo "Hello World! from testing"
        
      - name: Execute few commands
        run: |
          echo "Hello Messege1"
          echo "Hello Messege2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
        
      - name: List current folder
        run: ls -la
        
  my_testint2:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello Messege in my_testing2
        run: echo "Hello World! from testing2"
        
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
